POST http://localhost:8082/api/orders
Content-Type: application/json

{
  "customer": {
    "name": "dummy",
    "email": "dummy@email.com",
    "phone": "09987"
  },
  "deliveryAddress": {
    "addressLine1": "jalan1",
    "addressLine2": "jalan2",
    "city": "jakarta",
    "state": "state",
    "zipCode": "9987",
    "country": "IDN"
  },
  "items": [
    {
      "code": "P100",
      "name": "Product 1",
      "price": 34.0,
      "quantity": 1
    }
  ]
}

